#!/bin/sh -f
# Use this script to copy the dynamic libraries to lib subdir
# and put $SCWMDIR/modules/lib in your SCWM_LOAD_PATH
# ahead of the system libraries.
# This will let you test w/o installing
# Can give an argument to this script, too:
# e.g.,:
# make-devtest devlib
# then use $SCWMDIR/modules/devlib in your SCWM_LOAD_PATH
# so that your main Scwm does not crash
libdir=${1:-lib}
if [ ! -d $libdir ]; then
  mkdir $libdir
fi
cd $libdir
pwd
if [ ! -L app ]; then
  ln -sf . app
fi
if [ ! -L scwm ]; then
  ln -sf . scwm
fi
cd ..
setopt extended_glob
for i in **/lib*.so*~*lib/*(D); do
   rm $libdir/${i:t}
   cp $i $libdir  # does not preserve symlinks, but who cares
done

echo $SCWM_LOAD_PATH $GUILE_LOAD_PATH | grep -q $PWD  || 
  { print -u2 "Put `pwd`/$libdir in your SCWM_LOAD_PATH" }
