#!/uns/bin/zsh -f
# Use this script to copy the dynamic libraries to lib subdir
# and put $SCWMDIR/modules/lib in your GUILE_LOAD_PATH
# ahead of the system libraries.
# This will let you test w/o installing
if [ ! -d lib ]; then
  mkdir lib
fi
cd lib
if [ ! -L app ]; then
  ln -sf . app
fi
if [ ! -L scwm ]; then
  ln -sf . scwm
fi
cd ..
setopt extended_glob
cp  **/lib*.so*~lib/*(D) lib  # does not preserve symlinks, but who cares

echo $SCWM_LOAD_PATH $GUILE_LOAD_PATH | grep -q $PWD  || 
  { print -u2 "Put `pwd`/lib in your SCWM_LOAD_PATH" }
