#!/bin/sh -
# $Id$
# Quick hack -- pointers to general, better solutions?
# Any other packages have nice abstractions for this?

echo "uname -a:"; echo "------------------" 
uname -a
echo

echo "guile -v:"; echo "------------------"
guile -v
echo

echo "aclocal --version"; echo "------------------"
aclocal --version
echo

echo "autoconf --version"; echo "------------------"
autoconf --version
echo

echo "automake --version"; echo "------------------"
automake --version
echo

echo "libtool --version"; echo "------------------"
libtool --version
echo

echo "gcc --version"; echo "------------------"
gcc --version
echo

echo "g++ --version"; echo "------------------"
g++ --version
echo

echo "cassowary-config --version --cflags --gtllibs"; echo "------------------"
cassowary-config --version --cflags --gtllibs
echo

echo "scwm -V:"; echo "------------------"
./src/scwm -V
echo

echo "changed.c:"; echo "------------------"
cat src/changed.c
echo

echo "scwmpaths.h:"; echo "------------------"
cat src/scwmpaths.h
echo

echo "ldd scwm:"; echo "------------------"
if which ldd >/dev/null 2>&1; then
  ldd src/scwm
else
  echo "No ldd on this system."
fi
echo

echo "relevant env:"; echo "------------------"
env | egrep "(SCWM|^(LD_LIBRARY_)?PATH|GUILE)"
echo

echo "config.h:"; echo "------------------"
cat include/config.h
echo

echo "Please also see ./BUG-REPORTING" 1>&2
