.TH scwm-conf 1
.SH NAME
scwm \- configure the Scheme Constraints Window Manager
.SH SYNOPSIS
.B scwm-conf
.SH "DESCRIPTION"
This manual page briefly documents the
.BR scwm-conf
command.
.B scwm-conf
is a program that provides a GUI for configuring the
.B SCWM 
window manager.  The changes to the configuration
of 
.BR SCWM
are applied to the actual session of 
.BR SCWM
and saved in 
.BR ~/.scwm-options .
The next session of 
.BR SCWM
can so load these changes using the
.BR load-preferences
command.
.SH OPTIONS
No options are accepted at the command line.
.SH "SEE ALSO"
/usr/doc/scwm/README, scwm(1)
.SH COPYRIGHT
This manpage is copyrighted by Francesco Tapparo, and it is licensed under
the Gnu Public License.
There is absolutely NO WARRANTY.
.SH AUTHOR
This manual page was written by Francesco Tapparo, for the Debian
GNU/Linux system.
