// $Id$
// (C) 1999, 2000 Greg J. Badros
// Modified from gramsam.bnf, (C) 1999 IBM
// Use: fsgenum -f scwmgrammar.fsg
// To list all possible productions from this grammar

//--------------------------------------------------------------------
// A simple grammar for manipulating/changing the focus window
//
//  move window up <amount>
//  move window down <amount>
//  move window left <amount>
//  move window right <amount>
//
//  move window north east 
//
//  next window
//  previous window
//
//
//--------------------------------------------------------------------

<<command>> = <move_window> | <focus_switch> | <select_switch> | <window_command> | <misc> | <start_app> | <joke>.

<move_window> = move window <rel_or_absolute> .

<rel_or_absolute> = <relative> | <absolute> .

<relative> = <direction> <amount>? .

<direction> = up | down | left | right .

<amount> = five : 5 | ten : 10 | fifteen : 15 | twenty : 20 |
           "twenty five" : 25 | thirty : 30 | "thirty five" : 35 |
           forty : 40 | "forty five" : 45 | fifty : 50 | "one hundred" : 100.

<absolute> = north | south | east | west | "north east" | "north west" | "south east" | "south west" .


<focus_switch> = "focus" <next_prev> .

<select_switch> = "select" <next_prev> .

<next_prev> = <next> | <prev> .

<next> = "next" . // | "forward" .

<prev> = "previous" . // | "prior" | "back" .


<window_command> = "window" <window_action> .

<window_action> = "list" | "close" | "minimize" | "maximize" | "shade" | "select" .

<joke> = "jump" "down" "turn" "around" "pick" "a" "bale" "of" "cotton" .

<start_app> = "start" <application>  .

<application> = "emacs" | "term" | "logo" .

<misc> = "tile" | "cascade" | "remember" | "undo" .
