/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "scwm_scheme_evaluator.h"

#define GET_ATOM(x) G_STMT_START{ GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->decoder(&x, (GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur), sizeof(x)); GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ((guchar *)GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) + sizeof(x); }G_STMT_END
/***************** Begin module scwm_scheme_evaluator ***************/
void
scwm_scheme_evaluator_object_evaluate_sexp(scwm_scheme_evaluator_object _obj,
const CORBA_char * expr,
CORBA_char ** answer,
CORBA_char ** output,
CORBA_char ** error_output,
CORBA_Environment *ev)
{
GIOP_unsigned_long _ORBIT_request_id;
GIOPSendBuffer *_ORBIT_send_buffer;
GIOPRecvBuffer *_ORBIT_recv_buffer;
static const struct { CORBA_unsigned_long len; char opname[14]; } _ORBIT_operation_name_data = { 14, "evaluate_sexp" };
static const struct iovec _ORBIT_operation_vec = {(gpointer)&_ORBIT_operation_name_data, 18};
GIOPConnection *_cnx;


if(_obj->servant && _obj->vepv && scwm_scheme_evaluator_object__classid)
{
((POA_scwm_scheme_evaluator_object__epv *)_obj->vepv[scwm_scheme_evaluator_object__classid])->evaluate_sexp(_obj->servant, expr, answer, output, error_output, ev);
return;
}
_cnx = ORBit_object_get_connection(_obj);
retry_request:
_ORBIT_request_id = giop_get_request_id();
if((_cnx == NULL) || (_obj->active_profile == NULL)) {
CORBA_exception_set_system(ev, ex_CORBA_COMM_FAILURE, CORBA_COMPLETED_NO);
return;
}
_ORBIT_send_buffer = 
giop_send_request_buffer_use(_cnx, NULL,
				  _ORBIT_request_id, CORBA_TRUE, &(_obj->active_profile->object_key_vec),
				  &_ORBIT_operation_vec, &ORBit_default_principal_iovec);

if(!_ORBIT_send_buffer) {
CORBA_exception_set_system(ev, ex_CORBA_COMM_FAILURE, CORBA_COMPLETED_NO);
return;
}


  /* marshal parameter expr */
  {
    GIOP_unsigned_long len = expr?(strlen(expr)+1):0;
giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), 4);
  giop_send_buffer_append_mem_indirect(GIOP_SEND_BUFFER(_ORBIT_send_buffer), &len, sizeof(len));
    if(expr)
      giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), expr, len);
  }

giop_send_buffer_write(_ORBIT_send_buffer);
giop_send_buffer_unuse(_ORBIT_send_buffer);
_ORBIT_recv_buffer = giop_recv_reply_buffer_use_2(ORBit_object_get_connection(_obj), _ORBIT_request_id, TRUE);
if(_ORBIT_recv_buffer == NULL || _ORBIT_recv_buffer->message_buffer.message_header.message_type != GIOP_REPLY) {
CORBA_exception_set_system(ev, ex_CORBA_COMM_FAILURE, CORBA_COMPLETED_MAYBE);
    if(_ORBIT_recv_buffer) giop_recv_buffer_unuse(_ORBIT_recv_buffer);
return;
  }
if(_ORBIT_recv_buffer->message.u.reply.reply_status != GIOP_NO_EXCEPTION) {
if(_ORBIT_recv_buffer->message.u.reply.reply_status == GIOP_LOCATION_FORWARD) {
if(_obj->forward_locations != NULL)
ORBit_delete_profiles(_obj->forward_locations);
_obj->forward_locations = ORBit_demarshal_IOR(_ORBIT_recv_buffer);
_cnx = ORBit_object_get_forwarded_connection(_obj);
giop_recv_buffer_unuse(_ORBIT_recv_buffer);

goto retry_request;
} else {
ORBit_handle_exception(_ORBIT_recv_buffer, ev, NULL,_obj->orb);
giop_recv_buffer_unuse(_ORBIT_recv_buffer);
return;
  }
}
if(giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
/* demarshal parameter *answer */
  {
    GIOP_unsigned_long len;
  GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
  GET_ATOM(len);
    *answer = CORBA_string_alloc(len);
    if(len)
    strncpy(*answer,
GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur,
len);
    else
(*answer)[0] = '\0';
    GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ((guchar *)GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) + len;
  }
/* demarshal parameter *output */
  {
    GIOP_unsigned_long len;
  GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
  GET_ATOM(len);
    *output = CORBA_string_alloc(len);
    if(len)
    strncpy(*output,
GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur,
len);
    else
(*output)[0] = '\0';
    GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ((guchar *)GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) + len;
  }
/* demarshal parameter *error_output */
  {
    GIOP_unsigned_long len;
  GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
  GET_ATOM(len);
    *error_output = CORBA_string_alloc(len);
    if(len)
    strncpy(*error_output,
GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur,
len);
    else
(*error_output)[0] = '\0';
    GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ((guchar *)GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) + len;
  }
  } else {
/* demarshal parameter *answer */
  {
    GIOP_unsigned_long len;
  GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
  len = *((CORBA_unsigned_long *)GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur);
  GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ((guchar *)GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) + sizeof(CORBA_unsigned_long);
    *answer = CORBA_string_alloc(len);
    if(len)
    strncpy(*answer,
GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur,
len);
    else
(*answer)[0] = '\0';
    GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ((guchar *)GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) + len;
  }
/* demarshal parameter *output */
  {
    GIOP_unsigned_long len;
  GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
  len = *((CORBA_unsigned_long *)GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur);
  GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ((guchar *)GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) + sizeof(CORBA_unsigned_long);
    *output = CORBA_string_alloc(len);
    if(len)
    strncpy(*output,
GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur,
len);
    else
(*output)[0] = '\0';
    GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ((guchar *)GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) + len;
  }
/* demarshal parameter *error_output */
  {
    GIOP_unsigned_long len;
  GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
  len = *((CORBA_unsigned_long *)GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur);
  GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ((guchar *)GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) + sizeof(CORBA_unsigned_long);
    *error_output = CORBA_string_alloc(len);
    if(len)
    strncpy(*error_output,
GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur,
len);
    else
(*error_output)[0] = '\0';
    GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ((guchar *)GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) + len;
  }
  }

  giop_recv_buffer_unuse(_ORBIT_recv_buffer);
  ev->_major = CORBA_NO_EXCEPTION;
}

/***************** End module scwm_scheme_evaluator ***************/
