/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include "scwm_scheme_evaluator.h"
#define GET_ATOM(x) G_STMT_START{ GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->decoder(&x, (GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur), sizeof(x)); ((guchar *)GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += sizeof(x); }G_STMT_END

static const int zero_int = 0;
/***************** Begin module scwm_scheme_evaluator ***************/
CORBA_unsigned_long scwm_scheme_evaluator_object__classid = 0;

const struct CORBA_TypeCode_struct TC_scwm_scheme_evaluator_object_struct = {
{ { (ORBit_RootObject_Interface*)&ORBit_TypeCode_epv, TRUE, -1 }, ORBIT_PSEUDO_TYPECODE },
CORBA_tk_objref,"object","IDL:scwm_scheme_evaluator/object:1.0",
0,0,
NULL,
NULL,
NULL,
CORBA_OBJECT_NIL, 0, -1, 0, 0
};
/***************** End module scwm_scheme_evaluator ***************/
