/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <glib.h>
#define ORBIT_IDL_SERIAL 9
#include <orb/orbit.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* Begin CORBA module scwm_scheme_evaluator */

/* Begin interface scwm_scheme_evaluator_object */

  /* server-side (via the POA) data structures and methods */
#ifndef _POA_scwm_scheme_evaluator_object__vepv_defined
#define _POA_scwm_scheme_evaluator_object__vepv_defined

typedef struct _POA_scwm_scheme_evaluator_object__epv POA_scwm_scheme_evaluator_object__epv;
typedef struct {
  PortableServer_ServantBase__epv* _base_epv;
  POA_scwm_scheme_evaluator_object__epv *scwm_scheme_evaluator_object_epv;
} POA_scwm_scheme_evaluator_object__vepv;
#endif /* !_POA_scwm_scheme_evaluator_object__vepv_defined */

#ifndef _POA_scwm_scheme_evaluator_object_defined
#define _POA_scwm_scheme_evaluator_object_defined

typedef struct {
  void * _private;
  POA_scwm_scheme_evaluator_object__vepv* vepv;
} POA_scwm_scheme_evaluator_object;
#endif /* !_POA_scwm_scheme_evaluator_object_defined */

extern void POA_scwm_scheme_evaluator_object__init(POA_scwm_scheme_evaluator_object *servant, CORBA_Environment *ev);
extern void POA_scwm_scheme_evaluator_object__fini(POA_scwm_scheme_evaluator_object *servant, CORBA_Environment *ev);
  /* client-side data structures and methods */
#ifndef _scwm_scheme_evaluator_object_defined
#define _scwm_scheme_evaluator_object_defined

typedef CORBA_Object scwm_scheme_evaluator_object;
#define scwm_scheme_evaluator_object__free CORBA_Object__free
#endif /* !_scwm_scheme_evaluator_object_defined */

extern CORBA_unsigned_long scwm_scheme_evaluator_object__classid;
extern const struct CORBA_TypeCode_struct TC_scwm_scheme_evaluator_object_struct;
#define TC_scwm_scheme_evaluator_object (&TC_scwm_scheme_evaluator_object_struct)
extern void _ORBIT_skel_scwm_scheme_evaluator_object_evaluate_sexp(POA_scwm_scheme_evaluator_object *_ORBIT_servant, GIOPRecvBuffer *_ORBIT_recv_buffer, CORBA_Environment *ev, void(*_impl_evaluate_sexp)(PortableServer_Servant servant, const CORBA_char * expr, CORBA_char ** answer, CORBA_char ** output, CORBA_char ** error_output, CORBA_Environment *ev));
extern void scwm_scheme_evaluator_object_evaluate_sexp(scwm_scheme_evaluator_object _obj, const CORBA_char * expr, CORBA_char ** answer, CORBA_char ** output, CORBA_char ** error_output, CORBA_Environment *ev);

#ifndef _POA_scwm_scheme_evaluator_object__epv_defined
#define _POA_scwm_scheme_evaluator_object__epv_defined

struct _POA_scwm_scheme_evaluator_object__epv {
  void *_private;
  void (*evaluate_sexp)(PortableServer_Servant servant, const CORBA_char * expr, CORBA_char ** answer, CORBA_char ** output, CORBA_char ** error_output, CORBA_Environment *ev);
};
#endif /* !_POA_scwm_scheme_evaluator_object__epv_defined */

/* End interface scwm_scheme_evaluator_object */

/* End CORBA module scwm_scheme_evaluator */

#ifdef __cplusplus
}
#endif /* __cplusplus */

#undef ORBIT_IDL_SERIAL
