/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "scwm_scheme_evaluator.h"
#define GET_ATOM(x) G_STMT_START{ GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->decoder(&x, (GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur), sizeof(x)); GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ((guchar *)GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) + sizeof(x); }G_STMT_END
/***************** Begin module scwm_scheme_evaluator ***************/

void
_ORBIT_skel_scwm_scheme_evaluator_object_evaluate_sexp(POA_scwm_scheme_evaluator_object *_ORBIT_servant,
GIOPRecvBuffer *_ORBIT_recv_buffer,
CORBA_Environment *ev,
void (*_impl_evaluate_sexp)(PortableServer_Servant servant,
const CORBA_char * expr,
CORBA_char ** answer,
CORBA_char ** output,
CORBA_char ** error_output,
CORBA_Environment *ev))
{
  CORBA_char * expr;
  CORBA_char * answer;
  CORBA_char * output;
  CORBA_char * error_output;
  GIOPSendBuffer *_ORBIT_send_buffer;

  if(giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {


  /* demarshal parameter expr */
  {
    GIOP_unsigned_long len;
  GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
  GET_ATOM(len);
    expr = len?(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur):(((char *)GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) - sizeof(CORBA_unsigned_long));    GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ((guchar *)GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) + len;
  }
  } else {


  /* demarshal parameter expr */
  {
    GIOP_unsigned_long len;
  GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
  len = *((CORBA_unsigned_long *)GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur);
  GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ((guchar *)GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) + sizeof(CORBA_unsigned_long);
    expr = len?(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur):(((char *)GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) - sizeof(CORBA_unsigned_long));    GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ((guchar *)GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) + len;
  }
  }

_impl_evaluate_sexp(_ORBIT_servant, expr,
&(answer),
&(output),
&(error_output),
 ev);
  _ORBIT_send_buffer = 
    giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->connection, NULL,
	 _ORBIT_recv_buffer->message.u.request.request_id,
	 ev->_major);

if(ev->_major == CORBA_NO_EXCEPTION) {
  /* marshal parameter answer */
  {
    GIOP_unsigned_long len = answer?(strlen(answer)+1):0;
giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), 4);
  giop_send_buffer_append_mem_indirect(GIOP_SEND_BUFFER(_ORBIT_send_buffer), &len, sizeof(len));
    if(answer)
      giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), answer, len);
  }
  /* marshal parameter output */
  {
    GIOP_unsigned_long len = output?(strlen(output)+1):0;
giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), 4);
  giop_send_buffer_append_mem_indirect(GIOP_SEND_BUFFER(_ORBIT_send_buffer), &len, sizeof(len));
    if(output)
      giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), output, len);
  }
  /* marshal parameter error_output */
  {
    GIOP_unsigned_long len = error_output?(strlen(error_output)+1):0;
giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), 4);
  giop_send_buffer_append_mem_indirect(GIOP_SEND_BUFFER(_ORBIT_send_buffer), &len, sizeof(len));
    if(error_output)
      giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), error_output, len);
  }
} else if(ev->_major == CORBA_SYSTEM_EXCEPTION)
 ORBit_send_system_exception(_ORBIT_send_buffer, ev);else if(ev->_major == CORBA_USER_EXCEPTION)
 ORBit_send_user_exception(_ORBIT_send_buffer, ev, NULL);  giop_send_buffer_write(_ORBIT_send_buffer);
  giop_send_buffer_unuse(_ORBIT_send_buffer);
if(ev->_major == CORBA_NO_EXCEPTION)CORBA_free(answer);
if(ev->_major == CORBA_NO_EXCEPTION)CORBA_free(output);
if(ev->_major == CORBA_NO_EXCEPTION)CORBA_free(error_output);
}

static ORBitSkeleton get_skel_scwm_scheme_evaluator_object(POA_scwm_scheme_evaluator_object *servant,
GIOPRecvBuffer *_ORBIT_recv_buffer,
gpointer *impl)
{
gchar *opname = _ORBIT_recv_buffer->message.u.request.operation;

switch(opname[0]) {
case 'e':
*impl = (gpointer)servant->vepv->scwm_scheme_evaluator_object_epv->evaluate_sexp;
return (ORBitSkeleton)_ORBIT_skel_scwm_scheme_evaluator_object_evaluate_sexp;
break;
default: return NULL;
}
}

static void init_local_objref_scwm_scheme_evaluator_object(CORBA_Object obj, POA_scwm_scheme_evaluator_object *servant)
{
obj->vepv[scwm_scheme_evaluator_object__classid] = servant->vepv->scwm_scheme_evaluator_object_epv;
}
void POA_scwm_scheme_evaluator_object__init(POA_scwm_scheme_evaluator_object *servant,
CORBA_Environment *env)
{
  static const PortableServer_ClassInfo class_info = {(ORBit_impl_finder)&get_skel_scwm_scheme_evaluator_object, "IDL:scwm_scheme_evaluator/object:1.0", (ORBit_local_objref_init)&init_local_objref_scwm_scheme_evaluator_object};
  PortableServer_ServantBase__init(((PortableServer_ServantBase *)servant), env);
  ORBIT_OBJECT_KEY(servant->_private)->class_info = (PortableServer_ClassInfo*) &class_info;
if(!scwm_scheme_evaluator_object__classid)
scwm_scheme_evaluator_object__classid = ORBit_register_class(&class_info);
}

void POA_scwm_scheme_evaluator_object__fini(POA_scwm_scheme_evaluator_object *servant,
CORBA_Environment *env)
{
  PortableServer_ServantBase__fini(servant, env);
}

/***************** End module scwm_scheme_evaluator ***************/
