;;; AUTOMATICALLY-GENERATED BY extract-docs; DO NOT EDIT!
(define-module (app scwm user-options))

;; Each element of the list is '(var-name comment setter getter)
(define-public user-options (list
'(%load-path "The internal compiled-in loading path for scwm. " #f #f)
'(default-auto-raise-delay "Number of ms to delay before raising the window the mouse pointer entered.This can be overridden on a per-window basis using `set-auto-raise-delay!'." #f #f)
'(default-auto-raise-focus-proc "The default procedure to invoke when raising the window.This gets called after the auto-raise delay times out, and can be overwridden on a per-window basis using `set-auto-raise-focus-proc!'" #f #f)
'(default-auto-raise-unfocus-delay "Number of ms to delay before running the unfocus proc for a raised window.This can be overridden on a per-window basis using `set-auto-raise-unfocus-delay!'" #f #f)
'(default-auto-raise-unfocus-proc "The default procedure to invoke when un-raising the window.This gets called after the mouse pointer leaves an auto-raised window, andcan be overwridden on a per-window basis using `set-auto-raise-unfocus-proc!'" #f #f)
'(locale-fullname "Full name of the current locale, as a string. " #f #f)
'(locale-language-territory "The language territory name, as a string " #f #f)
'(opaque-move-percent "Percent of display area below which windows are moved opaquely." #f #f)
'(opaque-resize-percent "Percent of display area below which windows are resized opaquely." #f #f)
))
